### ISSUE TITLE
Register a contact person

### ISSUE THREAD

**Issue by mariasoria** [lean-mind/huella-positiva#14]
- Review if a contact person can be registered in the backend through the endpoint ([Help here](https://www.notion.so/Registrar-de-persona-de-contacto-1561c6d946e9411db41e2931720cd078))
- If this functionality is not implemented or it does not work properly, finish it.

**Comment by Marius9595** [comment]
This feature was implemented and works as expected through Requests (CODE 201 and Database record appears):

![image](https://user-images.githubusercontent.com/63452003/200194237-0d21b695-4a00-4335-a0de-c861f390e0d5.png)
![image](https://user-images.githubusercontent.com/63452003/200194334-73854326-4515-4379-882f-aa2b4898f62c.png)
![image](https://user-images.githubusercontent.com/63452003/200194296-33a8820c-16ca-4d4f-945a-e8f429ec489b.png)

**Comment by Marius9595** [comment]
The same problem in https://github.com/lean-mind/huella-positiva/issues/7#issuecomment-1304887069 happens for this feature
