### ISSUE TITLE
Create a proposal

### ISSUE THREAD

**Issue by mariasoria** [lean-mind/huella-positiva#15]
- Review if a proposal can be created in the backend through the endpoint (Help here(https://www.notion.so/Creaci-n-de-una-Proposal-20d0cf4f8fdf4ab6a1f6b711b6ff0047))
- If this functionality is not implemented or it does not work properly, finish it.

**Comment by Marius9595** [comment]
This functionality was implemented and works as expected (Response code 201 and database has got records, about a test proposal, created in tables expected).



# HTTP RESPONSE
<p align="center">
 <img  width=50% src="https://user-images.githubusercontent.com/63452003/203660025-5575f321-4378-40af-b505-3894a750d2dc.png">
</p>

# JSON SENT WITH PROPOSAL INFO

<p align="center">
 <img  width=50% src="https://user-images.githubusercontent.com/63452003/203662081-9eb0ff28-c152-4b4d-95c6-a358b5012a92.png">
</p>

# DATABASE
<p align="center">
 <img  width=80% src="https://user-images.githubusercontent.com/63452003/203660977-3d99c2c2-b747-4ab6-a0e6-273c7970a6a2.png">
</p>

<p align="center">
 <img  width=80% src="https://user-images.githubusercontent.com/63452003/203661386-807cf133-51ce-4cad-8b73-8e95a54257d5.png">
</p>


<p align="center">
 <img  width=80% src="https://user-images.githubusercontent.com/63452003/203661627-fad6dd3f-3647-423c-b635-2b2488aedf02.png">
</p>

# IMAGE SENT

<p align="center">
 <img  width=80% src="https://user-images.githubusercontent.com/63452003/203662302-1645b897-691a-42f9-a7ba-a13e0d9f70aa.png">
</p>
