### ISSUE TITLE
Enrol in a proposal

### ISSUE THREAD

**Issue by mariasoria** [lean-mind/huella-positiva#18]
- Review if a volunteer can enrol in a proposal in the backend through the endpoint.  (Regarding this, we need to check what is the next step after a volunteer enrols in a proposal: does he get an email? How does he know he has successfully enrolled? Does the ESAL/contact person receive any kind of confirmation?
- If this functionality is not implemented or it does not work properly, finish it.

**Comment by Marius9595** [comment]
@JuanAntonioQ  and I have tested by HTTP Request the ENDPOINT : `{{ROOT_URL}}/proposals/{{ID_PROPOSAL}}/join` as a Volunteer confirmed. This works as expected. However, there is not a confirmation for volunteer. EmailService is not used: [ACTION](https://github.com/lean-mind/huella-positiva/blob/main/backend/src/main/java/com/huellapositiva/domain/actions/JoinProposalAction.java)


# HTTP REQUEST 
<p align="center" >
   <img width="70%" src ="https://user-images.githubusercontent.com/63452003/206280108-f4eaf0d4-b642-431d-98b3-89c432a6cc5a.png">
</p>


# DATABASE RECORDS TO VISUALIZE FUNCTIONALITY
<p align="center" >
   <img width="70%" src ="https://user-images.githubusercontent.com/63452003/206280427-1abdc223-7472-46a3-8c20-cea561572ded.png">
</p>

<p align="center" >
   <img width="70%" src ="https://user-images.githubusercontent.com/63452003/206280624-c48045e0-57c1-437d-8b86-5105b3d42a9e.png">
</p>

<p align="center" >
   <img width="70%" src ="https://user-images.githubusercontent.com/63452003/206280742-d72455dd-d0a3-40b5-96f5-ac870ae77cdb.png">
</p>

# TEST OF FUNCTIONALITY (It is passing)
<p align="center" >
   <img width="70%" src ="https://user-images.githubusercontent.com/63452003/206281397-2bbf31e3-aa05-4a4b-b6b8-3ae48c647c2b.png">
</p>
