### ISSUE TITLE
Create a docker-compose to simplify workspace

### ISSUE THREAD

**Issue by mariasoria** [lean-mind/huella-positiva#28]
We need to simplify the way to running the application in local.

The final result expected is use a command like

```shell
make up
```

And application up the database, backend and frontend

## Resources
- [Building Java applications using Maven and Docker (multi-stage builds)](https://scalabledeveloper.com/posts/building-java-applications-using-maven-and-docker-multi-stage-builds/)

**Comment by RubenZagon** [comment]
https://github.com/lean-mind/huella-positiva/pull/29
