### ISSUE TITLE
Prepare endpoints file ready to import

### ISSUE THREAD

**Issue by mariasoria** [lean-mind/huella-positiva#5]
A json file needs to be prepare with all endpoints ready to import into postman/insomnia.
Environments configurations needs to be included too.

**Comment by Marius9595** [comment]
Hi!  ApiRequest files were created. They are almost all mvp features

https://github.com/lean-mind/huella-positiva/tree/main/backend/APIRequests

**Comment by CrisKrus** [comment]
This sounds as a good idea to store it in the repository 

https://www.jetbrains.com/help/idea/exploring-http-syntax.html

**Comment by Marius9595** [comment]
We have them [here](https://github.com/lean-mind/huella-positiva/tree/main/backend/APIRequests) :D

**Comment by mariasoria** [comment]
A json file has been created from the swagger documentation and will be added to the source code. Besides, the README.md will need to be updated as well.
