### ISSUE TITLE
Register a volunteer

### ISSUE THREAD

**Issue by mariasoria** [lean-mind/huella-positiva#9]
- Review if the form to register a volunteer is shown and it works
- If this functionality is not implemented or it does not work properly, finish it

**Comment by Oiranca** [comment]
The express register volunteers work correctly into localhost but don't show errors messages when is necessary, for example, this email exists in the database.

![Register_voluteers_express_form](https://user-images.githubusercontent.com/55623374/202686814-8cb68a2b-b708-4fd8-9b26-3dd6e069234b.png)
![credentials_table](https://user-images.githubusercontent.com/55623374/202686858-fea0cde4-0923-41dc-aa07-328dc1763fed.png)
